name: Android Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    uses: Assembles-J/.github/.github/workflows/android-build.yml@main
    with:
      java-version: '17'
      working-directory: android
      gradle-task: assembleDebug
      artifact-name: ev-charge-book-debug-apk
      artifact-path: android/**/build/outputs/apk/**/*.apk
